import React from 'react';
import { FileText, Download, Activity } from 'lucide-react';
import { jsPDF } from 'jspdf';

export const ProjectReport: React.FC = () => {
  const generatePDF = () => {
    const doc = new jsPDF();
    const title = "Project Report: Smart Health AI";
    const developer = "Developer: Harish Masilamani";
    const date = `Date: ${new Date().toLocaleDateString()}`;

    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233); // medical-blue
    doc.text(title, 20, 20);

    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(developer, 20, 30);
    doc.text(date, 20, 37);

    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(20, 45, 190, 45);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text("1. Project Overview", 20, 55);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85); // slate-700
    const overview = "Smart Health AI is a cutting-edge, web-based healthcare application designed to provide early disease detection and health monitoring through a combination of user-reported symptoms and real-time facial analysis. The application leverages rule-based AI classification to offer personalized health insights, medical recommendations, and emergency guidance.";
    const overviewLines = doc.splitTextToSize(overview, 170);
    doc.text(overviewLines, 20, 62);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("2. Objectives", 20, 85);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text("- Early Detection: Preliminary assessment of potential health issues.", 20, 92);
    doc.text("- Non-Invasive Monitoring: Facial analysis for stress, dehydration, and fatigue.", 20, 98);
    doc.text("- Accessibility: Multi-language interface for global reach.", 20, 104);
    doc.text("- Emergency Support: Critical alerts and hospital finder.", 20, 110);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("3. Tech Stack", 20, 125);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text("- Frontend: React 18 (TypeScript)", 20, 132);
    doc.text("- Styling: Tailwind CSS", 20, 138);
    doc.text("- Animations: Motion", 20, 144);
    doc.text("- Icons: Lucide React", 20, 150);
    doc.text("- PDF Generation: jsPDF", 20, 156);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("4. Key Features", 20, 171);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text("- AI Prediction Engine: Processes 10+ symptoms and health data.", 20, 178);
    doc.text("- Real-Time Face Analysis: Tiredness, Stress, Redness, Dehydration, Heart Feelings, Confusion.", 20, 184);
    doc.text("- Multi-Language: Support for English, Tamil, Hindi, Telugu, Japanese, Korean.", 20, 190);
    doc.text("- Hospital Finder: GPS-based tracking of medical facilities.", 20, 196);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("5. Privacy & Security", 20, 211);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const privacy = "All processing is done client-side. The camera feed and health data are processed in the user's browser and are never transmitted to a server, ensuring 100% data privacy.";
    const privacyLines = doc.splitTextToSize(privacy, 170);
    doc.text(privacyLines, 20, 218);

    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text("Report generated by Smart Health AI System. Developer: Harish Masilamani", 20, 280);
    doc.text("https://harishmasilamani.lovable.app", 20, 285);

    doc.save("Smart_Health_AI_Project_Report.pdf");
  };

  return (
    <div className="glass-card p-8 flex flex-col items-center gap-6 text-center">
      <div className="w-16 h-16 rounded-2xl bg-medical-blue/10 flex items-center justify-center">
        <FileText className="w-8 h-8 text-medical-blue" />
      </div>
      <div>
        <h3 className="text-2xl font-display font-bold mb-2">Project Report</h3>
        <p className="text-slate-400 max-w-md">
          Download the comprehensive technical report for the Smart Health AI project in PDF format.
        </p>
      </div>
      <button 
        onClick={generatePDF}
        className="btn-primary flex items-center gap-2"
      >
        <Download size={18} />
        Download PDF Report
      </button>
    </div>
  );
};
